### ISSUE TITLE
Missing SafeSurf Configuration 

### ISSUE THREAD

**Issue by pouyashahrdami** [na-stewart/FreeSafeSurf#14]
### Description
------------------------------
SafeSurf.config Not Found -  missing  [System.IO.FileNotFoundException]

### Location 
Config.cs File

**Comment by na-stewart** [comment]
Does this happen while running the compiled application or did you clone it? @pouyashahrdami

**Comment by na-stewart** [comment]
The config file is created once settings are confirmed via the UI.
